env:
    - PYTHONWARNINGS="ignore:Unverified HTTPS request"
language: python
python:
    - "3.6"      # current default Python on Travis CI
install:
    - pip install -r requirements.dev.txt
    - pip install -r requirements.txt

script:
    - pytest
